# Generated by Django 5.1.7 on 2025-04-14 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('idAsignatura', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Aulas',
            fields=[
                ('idAula', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('idCurso', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Dias',
            fields=[
                ('idDia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FranjaHoraria',
            fields=[
                ('idFranjaHoraria', models.AutoField(primary_key=True, serialize=False)),
                ('numeroFranja', models.IntegerField(max_length=2)),
                ('descripcion', models.CharField(max_length=50)),
                ('esRecreo', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('idProfesor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido1', models.CharField(max_length=50)),
                ('apellido2', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=50)),
                ('contrasenia', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('idHorario', models.AutoField(primary_key=True, serialize=False)),
                ('esGuardia', models.BooleanField(default=False)),
                ('idAsignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.asignatura')),
                ('idAula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.aulas')),
                ('idCurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cursos')),
                ('idDia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.dias')),
                ('idProfesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.profesor')),
            ],
        ),
    ]
