# Generated by Django 5.1.7 on 2025-04-17 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_profesor_groups_profesor_is_active_profesor_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesor',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='profesor',
            name='contrasenia',
            field=models.CharField(max_length=128),
        ),
    ]
