# Generated by Django 5.1.7 on 2025-04-17 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_profesor_groups_remove_profesor_is_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profesor',
            old_name='nombre',
            new_name='username',
        ),
    ]
