# Generated by Django 5.1.7 on 2025-04-17 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_nombre_profesor_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profesor',
            old_name='username',
            new_name='nombre',
        ),
    ]
