# Generated by Django 5.1.7 on 2025-04-17 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_username_profesor_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesor',
            name='contrasenia',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='last_login',
        ),
        migrations.AlterField(
            model_name='profesor',
            name='correo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
