# Generated by Django 5.1.7 on 2025-04-29 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_profesor_esadmin_profesor_iduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignatura',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
