# Generated by Django 5.1.7 on 2025-05-13 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_horario_idfranja'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
