# Generated by Django 5.1.7 on 2025-05-15 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_horario_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ausencia',
            fields=[
                ('idAusencia', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('comentario', models.TextField(blank=True)),
                ('horario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.horario')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.profesor')),
            ],
        ),
        migrations.AddField(
            model_name='horario',
            name='idAusencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='main.ausencia'),
        ),
    ]
