# Generated by Django 5.1.7 on 2025-05-17 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_ausencia_horario_idausencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='ausencia',
            name='justificada',
            field=models.BooleanField(default=False),
        ),
    ]
