# Generated by Django 5.1.7 on 2025-06-06 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_ausencia_justificada'),
    ]

    operations = [
        migrations.AddField(
            model_name='franjahoraria',
            name='horaFin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='franjahoraria',
            name='horaInicio',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
