# Generated by Django 5.1.7 on 2025-06-06 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_franjahoraria_horafin_franjahoraria_horainicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='franjahoraria',
            name='horaFin',
        ),
    ]
