# Generated by Django 5.1.7 on 2025-06-10 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_ausencia_horario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ausencia',
            name='justificada',
        ),
        migrations.AddField(
            model_name='ausencia',
            name='idFranja',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.franjahoraria'),
        ),
    ]
