# Generated by Django 5.1.7 on 2025-06-10 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_remove_ausencia_justificada_ausencia_idfranja'),
    ]

    operations = [
        migrations.AddField(
            model_name='ausencia',
            name='justificada',
            field=models.BooleanField(default=False),
        ),
    ]
